- name: Test the hostname file
  hosts: add
  tasks:
#     - name: /data/install/monitor/
#       file: dest=/data/install/monitor mode=755 owner=root group=root state=directory    
     - name: copy mysqlmonitor.sh
       copy: src=/data/install/monitor/mysql_monitor/mysqlmonitor.sh   dest=/data/install/monitor/
#     - name: copy iostat
#       copy: src=/data/install/monitor/iostat   dest=/data/install/monitor
     - name:  mysqlmonitor.sh
       shell: cd /data/install/monitor/;sh mysqlmonitor.sh
#     - name: /etc/zabbix/scripts
#       file: dest=/etc/zabbix/scripts  mode=755 owner=root group=root state=directory   
#     - name:  init.sh
#       shell: cd /data/install/monitor/iostat;sh init.sh
 
