- name: rsync config
  hosts: '{{ hosts }}'
  tasks:

     - name: copy rsyncd.conf
       copy: src=rsyncd.conf dest=/usr/local/etc/rsync/etc/ group=root owner=root

     - name: copy  rsyncd.secrets
       copy: src=rsyncd.secrets dest=/usr/local/etc/rsync/ group=root owner=root mode=600

     - name: rsyncd restart
       service: name=rsyncd state=restarted

     - name: copy  067.sync.default
       copy: src=067.sync.default dest=/usr/local/etc/iptables_rules group=root owner=root

     - name: iptables restart
       service: name=iptables state=restarted

     - name: iptables rsyncd
       service: name=rsyncd state=restarted
