- name: deploy yum
  hosts: '{{ hosts }}'
  tasks:

      #    - name: copy ambari-2.4.2.repo
      #copy: src=ambari-2.4.2.repo dest=/etc/yum.repos.d/ambari.repo
    - name: copy ambari-2.5.1.repo
      copy: src=ambari-2.5.1.repo dest=/etc/yum.repos.d/ambari.repo

    - name: yum clean all
      shell: yum clean all
