- name: redis monitor
  hosts: rdb1v.infra.bjza.pdtv.it
  tasks:
   - name: yum zabbix-agent
     yum:  name=zabbix-agent  state=installed
   - name: Add repository
     yum_repository:
       name: epelzabbix
       description: EPEL YUM repo
       baseurl: http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm
